smart = {1:' Raw_Read_Error_Rate (Raw Value)',
1:' Raw_Read_Error_Rate ',
2:' Throughput_Performance (Raw Value)',
2:' Throughput_Performance ',
3:' Spin_Up_Time (Raw Value)',
3:' Spin_Up_Time ',
4:' Start_Stop_Count (Raw Value)',
4:' Start_Stop_Count ',
5:' Reallocated_Sector_Ct (Raw Value)',
5:' Reallocated_Sector_Ct ',
7:' Seek_Error_Rate (Raw Value)',
7:' Seek_Error_Rate ',
8:' Seek_Time_Performance (Raw Value)',
8:' Seek_Time_Performance ',
9:' Power_On_Hours (Raw Value)',
9:' Power_On_Hours ',
10:' Spin_Retry_Count (Raw Value)',
10:' Spin_Retry_Count ',
11:' Calibration_Retry_Count (Raw Value)',
11:' Calibration_Retry_Count ',
12:' Power_Cycle_Count (Raw Value)',
12:' Power_Cycle_Count ',
22:' Current Helium Level ',
183:' Runtime_Bad_Block (Raw Value)',
183:' Runtime_Bad_Block ',
184:' End-to-End_Error (Raw Value)',
184:' End-to-End_Error ',
187:' Reported_Uncorrect (Raw Value)',
187:' Reported_Uncorrect ',
188:' Command_Timeout (Raw Value)',
188:' Command_Timeout ',
189:' High_Fly_Writes (Raw Value)',
189:' High_Fly_Writes ',
190:' Airflow_Temperature_Cel (Raw Value)',
190:' Airflow_Temperature_Cel ',
191:' G-Sense_Error_Rate (Raw Value)',
191:' G-Sense_Error_Rate ',
192:' Power-Off_Retract_Count (Raw Value)',
192:' Power-Off_Retract_Count ',
193:' Load_Cycle_Count (Raw Value)',
193:' Load_Cycle_Count ',
194:' Temperature_Celsius (Raw Value)',
194:' Temperature_Celsius ',
195:' Hardware_ECC_Recovered (Raw Value)',
195:' Hardware_ECC_Recovered ',
196:' Reallocated_Event_Count (Raw Value)',
196:' Reallocated_Event_Count ',
197:' Current_Pending_Sector (Raw Value)',
197:' Current_Pending_Sector ',
198:' Offline_Uncorrectable (Raw Value)',
198:' Offline_Uncorrectable ',
199:' UDMA_CRC_Error_Count (Raw Value)',
199:' UDMA_CRC_Error_Count ',
200:' Multi_Zone_Error_Rate (Raw Value)',
200:' Multi_Zone_Error_Rate ',
220: ' Disk shift ',
222: ' Loaded Hours ',
224: ' Load Friction ',
226: ' Load In-time ',
240:' Head_Flying_Hours (Raw Value)',
240:' Head_Flying_Hours ',
241:' Total_LBAs_Written (Raw Value)',
241:' Total_LBAs_Written ',
242:' Total_LBAs_Read (Raw Value)',
242:' Total_LBAs_Read '}