smart = {1:' Raw_Read_Error_Rate (Raw Value)',
1:' Raw_Read_Error_Rate (Normalized Value)',
2:' Throughput_Performance (Raw Value)',
2:' Throughput_Performance (Normalized Value)',
3:' Spin_Up_Time (Raw Value)',
3:' Spin_Up_Time (Normalized Value)',
4:' Start_Stop_Count (Raw Value)',
4:' Start_Stop_Count (Normalized Value)',
5:' Reallocated_Sector_Ct (Raw Value)',
5:' Reallocated_Sector_Ct (Normalized Value)',
7:' Seek_Error_Rate (Raw Value)',
7:' Seek_Error_Rate (Normalized Value)',
8:' Seek_Time_Performance (Raw Value)',
8:' Seek_Time_Performance (Normalized Value)',
9:' Power_On_Hours (Raw Value)',
9:' Power_On_Hours (Normalized Value)',
10:' Spin_Retry_Count (Raw Value)',
10:' Spin_Retry_Count (Normalized Value)',
11:' Calibration_Retry_Count (Raw Value)',
11:' Calibration_Retry_Count (Normalized Value)',
12:' Power_Cycle_Count (Raw Value)',
12:' Power_Cycle_Count (Normalized Value)',
22:' Current Helium Level (Normalized Value)',
183:' Runtime_Bad_Block (Raw Value)',
183:' Runtime_Bad_Block (Normalized Value)',
184:' End-to-End_Error (Raw Value)',
184:' End-to-End_Error (Normalized Value)',
187:' Reported_Uncorrect (Raw Value)',
187:' Reported_Uncorrect (Normalized Value)',
188:' Command_Timeout (Raw Value)',
188:' Command_Timeout (Normalized Value)',
189:' High_Fly_Writes (Raw Value)',
189:' High_Fly_Writes (Normalized Value)',
190:' Airflow_Temperature_Cel (Raw Value)',
190:' Airflow_Temperature_Cel (Normalized Value)',
191:' G-Sense_Error_Rate (Raw Value)',
191:' G-Sense_Error_Rate (Normalized Value)',
192:' Power-Off_Retract_Count (Raw Value)',
192:' Power-Off_Retract_Count (Normalized Value)',
193:' Load_Cycle_Count (Raw Value)',
193:' Load_Cycle_Count (Normalized Value)',
194:' Temperature_Celsius (Raw Value)',
194:' Temperature_Celsius (Normalized Value)',
195:' Hardware_ECC_Recovered (Raw Value)',
195:' Hardware_ECC_Recovered (Normalized Value)',
196:' Reallocated_Event_Count (Raw Value)',
196:' Reallocated_Event_Count (Normalized Value)',
197:' Current_Pending_Sector (Raw Value)',
197:' Current_Pending_Sector (Normalized Value)',
198:' Offline_Uncorrectable (Raw Value)',
198:' Offline_Uncorrectable (Normalized Value)',
199:' UDMA_CRC_Error_Count (Raw Value)',
199:' UDMA_CRC_Error_Count (Normalized Value)',
200:' Multi_Zone_Error_Rate (Raw Value)',
200:' Multi_Zone_Error_Rate (Normalized Value)',
220: ' Disk shift (Normalized Value)',
222: ' Loaded Hours (Normalized Value)',
224: ' Load Friction (Normalized Value)',
226: ' Load In-time (Normalized Value)',
240:' Head_Flying_Hours (Raw Value)',
240:' Head_Flying_Hours (Normalized Value)',
241:' Total_LBAs_Written (Raw Value)',
241:' Total_LBAs_Written (Normalized Value)',
242:' Total_LBAs_Read (Raw Value)',
242:' Total_LBAs_Read (Normalized Value)'}